### ISSUE TITLE
Invoke shell, or bash?

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#11]
I noticed John was using "#!/bin/sh" in scripts "in the hope that dash will be used". 

Should all the pipemenus use this?

**Comment by johnraff** [comment]
Entirely up to you. If there are "bashisms" (like [[...]] instead of [...]) then you need bash. If there's an execution speed issue (as there was with the places menu) then a switch to dash will speed things up quite a bit, but some constructions will be ruled out.

"Places" had to pup up a menu almost instantaneously even for a big directory full of odd files and subdirectories. Other pipe menus might not be so pushed for speed. Also, hardware is now faster than it was when "places" was written.

In general, if you don't need bash then it makes your scripts more portable to use the generic shell.

**Comment by AlexDaniel** [comment]
Yeah, but "more portable" is not required in our case, right? Also, by not using bash features you are making your code less readable and more error-prone, so please stick to bash (and its features) unless you really know what you're doing ([BashPitfalls](http://mywiki.wooledge.org/BashPitfalls) is a good start to add more sense to your scripts).  In case of pipemenus it was proven (although some people are probably still not convinced) that switching from bash to sh does not bring a good enough speedup compared to better code style and less use of dependencies. Also, if you need more speed, you can try using something more advanced (perl comes to mind).

**Comment by ghost** [comment]
On Debian, for the average user, it doesn't really matter if you do #!/bin/bash or #!/bin/sh in scripts. Bash and dash (to which /bin/sh is linked by default IIRC) however differ in execution speed; dash can be significantly faster -- I do notice the speed difference even on a i5 @ 2,9Ghz, I use dash as a shell for procmail etc. It should be up to the developer to decide what shell he wants to use. Both are available most of the time anyway.

**Comment by capn-damo** [comment]
I'll leave it as it is then :)
