### ISSUE TITLE
x-terminal-emulator title option argument

### ISSUE THREAD

**Issue by cpoakes** [BunsenLabs/bunsen-pipemenus#15]
The pipemenu installers invoke the terminal emulator with a title for a professional appearance.  The  scripts use option argument "--title".  While supported by the common GTK compliant terminal emulators (xfce4-terminal, roxterm, lxterminal, terminator), this option is not supported by xterm 
and rxvt/urxvt. Fortunately, all of these emulators support the legacy "-T" option originating with xterm.  As the x-terminal-emulator can be mapped to any one of these alternatives, "-T" not "--title" should be the standard option for specifying a title.

**Comment by capn-damo** [comment]
It hadn't occurred to me! I'll edit and add a "-T"

**Comment by johnraff** [comment]
The --title option had been tested with urxvt, and works. However, since -T works too, and in fact is the required option for compliance with the Debian requirements for x-terminal-emulator ( https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s11.8.3 ) then, agreed, we should switch to -T.
