### ISSUE TITLE
Terminal execute command syntax errors

### ISSUE THREAD

**Issue by cpoakes** [BunsenLabs/bunsen-pipemenus#17]
The "-e" (execute) option argument  is supported across the range of common programs used for the x-terminal-emulator, but the invocation is not uniform. It may be quoted or unquoted:

```
x-terminal-emulator -e "man tint2"              
x-terminal-emulator -e man tint2                
```

Some emulators require one form or the other, with no common denominator:

```
                Only            Only                            Unquoted
                quoted          unquoted        Either          using "-x"
xterm                                           X               NA
urxvt                           X                               NA
xfce4-terminal  X                                               X
lxterminal                                      X               NA
roxterm                         X                               NA
terminator      X                                               X
```

Note that all emulators requiring quotes with "-e" also accept unquoted versions using "-x" in place of "-e" (as noted).  The pipemenus need to set correct -e/-x (or quoted/unquoted) commands to accommodate all x-terminal-emulator alternatives.

**Comment by Sector11** [comment]
How many terminals are there going to be in Bunsen?

**Comment by capn-damo** [comment]
Just one emulator I guess, but it makes sense that the utility scripts should work with any others that a user may install.
It could be a lot of work though, if quoted/unquoted is important, because of quoted commands within other scripts.

**Comment by cpoakes** [comment]
Just reviewed forum discussion, last johnraff was leaning toward xfce4-terminal as the default for x-terminal-emulator. (I note other terminals were mentioned that I did not include in my tests: sakura, mate-terminal).  However, if we are going to use x-terminal-emulator, we should support any valid choice.  Otherwise we should create bl-terminal-emulator alternative to restrict the set of possibilities.

**Comment by johnraff** [comment]
x-terminal-emulator is _required_ to support the unquoted variation, ie what comes after the -e is a command and its arguments. 
https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s11.8.3

xfce4-terminal does in fact support that _when called as x-terminal-emulator_ because what is actually registered with debian alternatives is a wrapper script xfce4-terminal.wrapper. All other terminals providing x-terminal-emulator should support that syntax either natively or through such a wrapper script.

(The failure of Terminator on Wheezy to support that syntax, although registering itself as an x-terminal-emulator alternative, was a long-standing bug which has been fixed on its Jessie version.)

**Comment by cpoakes** [comment]
@johnraff - I appreciate your thoroughness in finding the policy docs and pointing out the function of the wrapper script (and the -T requirement on the other issue).  FYI: Mate-terminal and gnome-terminal share the same limitation and also provide a wrapper.  Sakura as x-terminal-emulator supports -e, but does NOT support -T (Debian bug report filed).
