### ISSUE TITLE
Is an "install" option always needed?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-pipemenus#18]
Do pipemenus need an "install" entry in every case for apps not on the user's system? If it's something (s)he has no intention of installing it will clutter up the menu unnecessarily. 

Maybe we could give some thought to which cases justify an "install" and which can just be omitted from the menu if they're not installed? (Of course those entries would appear after the app was installed.)

eg Add "install" option if the installation is more complicated than a simple apt-get, or if it's something we are recommending the user to install...?

**Comment by capn-damo** [comment]
As I said somewhere else (can't remember where), several of proposed applications for the post-install script could be in the menu instead eg GIMP, LO. The post-install script can then just deal with things like java, dev tools, printers.

The forums are always full of suggestions for `app1 || app2 || app3`, so a couple of "install app" menu items are a reasonable idea imo, especially for new users. Editing the menu is very easy because of the APPS line at the beginning:
`# In order to add another APP, add the package name to this array:`
`APPS=( 'app1' 'app2' 'app3' )`

Suggestion:  Some HowTo docs could be added to the Help menu for common noob questions eg "HowTo edit the Openbox Menu", opens in the editor or terminal.

**Comment by johnraff** [comment]
Yes simple and obvious installs like Gimp and LO should be in the menu rather than -welcome, agreed.

Also agree that suggested installs can be very useful for new users. I discovered some nice apps through adopting CrunchBang. The choice in the repos is so huge it really helps if someone a bit more experienced can point to the more useful and less broken ones.

I was wondering, though, if there might be one or two candidates for leaving out an "install" entry in the menu (entry appearing after installation) - in particular, cases where groups of apps were alternatives rather than incremental enhancements, so to speak. In such cases users will choose one and might be irritated always being prompted to install another. If there are any such cases that is... I'll have to install all the latest pipemenus and actually try them out.

Editing: one difference from the OB menu.xml is that the pipemenu is a system file, not a user file. It would either need to be edited as root or copied into user space and relinked. In the first case any changes would be overwritten by an upgrade (bugfix or improvement), in the second, such upgrades would not get through to the user. So while it is basically easy, I think we should make efforts for system-supplied menus not to need user editing as far as possible.

Adding some built-in how-to docs to be brought up by the help menu sounds like a good idea. (Someone would have to write them though.) Alternatively, link to a related forum post, if there is one.

**Comment by capn-damo** [comment]
@johnraff "So while it is basically easy, I think we should make efforts for system-supplied menus not to need user editing as far as possible."

A solution: 
Using the graphics pipemenu as an example, have a file  `~/.config/openbox/menu-graphics.cfg`, which has 
`# In order to add another APP, add the package name to the array:`
`TOOLS=( 'mirage' 'gimp' 'blender' 'inkscape' 'mandelbulber' 'viewnior')`
`SCROTS=('xfce4-screenshooter' 'scrot')`

Then read the VARS into the pipemenu at the beginning, with:
`source ".config/openbox/menu-graphics.cfg"`

Some of the other pipemenus can be configured the same way, so the system pipemenus don't need to be edited by the user.

---

"Adding some built-in how-to docs to be brought up by the help menu sounds like a good idea. (Someone would have to write them though.) Alternatively, link to a related forum post, if there is one"

I've tested this, and it is simple to implement. A quick HowTo opening in a zenity textinfo window is better than a link imo - there is online help in the Help pipemenu anyway. I was thinking along the lines of a menu entry at the bottom: "How to edit Menu" :)
I'm happy to put some helpfiles together - should they go in bunsen-docs? (What would the filepath be for the menuitem command?)

**Comment by johnraff** [comment]
User config files sounds like a great idea. (Unless someone points out a snag.) As I suggested elsewhere, maybe put them all into one file (requiring different names for the arrays)?

To date there's been no discussion of the content of bunsen-docs. As to the filepaths, I'm guessing that we'll have to choose between /usr/share/bunsen/bunsen-docs and /usr/share/doc/bunsen-docs
Maybe the latter? Opinions?

Anyway, yes, please make some helpfiles if you have the time. We can then think about where to put them.

Another thought - since all the pipemenus are sourcing bl-include.cfg we should perhaps be putting things like BL_COMMON_LIBDIR and USR_CFG (or perhaps USR_CFG_DIR, based on the XDG default), along with a possible DOCS_DIR, in there, so all can use them, and any change would just have to be in one file?

Also, as mentioned elsewhere, I'm not quite sure if .cfg is the most appropriate file ending for a file holding shell commands. ...something.rc perhaps?

**Comment by johnraff** [comment]
A bit of googling also suggests these other possible paths for helpfiles:
/usr/share/help/{C,en}/bunsen-docs/help
/usr/share/bunsen/bunsen-docs/help
/usr/share/bunsen/help/en/

Perhaps /usr/share/doc is meant for info _about_ the specific package, rather than general helpfiles?

Maybe this is the one:
/usr/share/bunsen/bunsen-docs/help
or
/usr/share/bunsen/bunsen-docs/help/en/ (Prepare for i18n?)
So stuff installed by bunsen-docs goes in a bunsen-docs directory?
