### ISSUE TITLE
In bl-conky-pipemenu, set default conky to something in ~/.config/conky ? 

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-pipemenus#26]
There will be a symlink from ~/.conkyrc to wherever the default conky really is, but mightn't it be better if scripts all refer to the real location?
ie change `CONKYDEFAULT="$HOME/.conkyrc"` to something like `CONKYDEFAULT="$CONKYPATH/default"` ? Looks a bit neater, and allows CONKYPATH to be changed more easily.

In fact, it might be possible for the pipemenu to check for the existence of that symlink at ~/.conkyrc and make it if necessary, and if there's already a conky config file there, to move it to the new location?

**Comment by capn-damo** [comment]
What if a user has replaced the symlink with their own `~/.conkyrc`? We shouldn't be touching that surely?

Are you suggesting the default conkyrc should just be called `default`? The script would then need more test conditions when searching for conkys to add to the displayed list, because it looks for files ending with `conky` or `conkyrc`. 
If it was called something like `default.conkyrc` instead?

**Comment by Sector11** [comment]
???  The reason I put the conkys in ~/.config/conky was because it was discussed in the "conkySwitcher Pipemenu" and John came out as a strong supporter of that.

Things are snowballing here.  John your little script is a few steps up from conkywonky as are the ssc scripts at ConkyPitstop, but they only work with conkys (there).  Your script stops and restarts a "process" vs just a conky.

But that isn't what "Conky Chooser" does.

Example:
BL-Text.conkyrc & BL-Default.conkyrc are running
http://postimg.org/image/47e5l29xl/
Opening Conky Chooser shows them as checked - leaving them checked will assure they remain running.
1. de-slecting BL-Default.conkyrc, and
2. checking BL-Ellipsees-Grey.conkyrc and CB-Right.conkyrc
http://postimg.org/image/kwflgz6ix/

So Conky Chooser allows one to stop a specific conky (process - tint2 as damo is working on) and start another or mix and match which are stopped and which are started.

**Comment by johnraff** [comment]
Yes things are getting a bit complex...

First, my general-purpose restarter script now looks unnecessary, at least for conky and tint2. If I've got it right, conky-chooser (is that the same as bl-conkyzen?) does all the restarting needed? (In fact, the recent conkys are supposed not to need restarting after a config file edit, but I seem to recall a post saying it was still sometimes needed.)

I'm guessing the same goes for tint2, so the menu entry "restart tint2" can disappear?

@capn-damo, I said:

> In fact, it might be possible for the pipemenu to check for the existence of that symlink at ~/.conkyrc and make it if necessary, and if there's already a conky config file there, to move it to the new location?"

There are two things:
1) What the _installer_ should set up initially. At this point the user hasn't made any files anywhere, right? Unless we're talking about an installer that can be run on top of an already working system? That might not be impossible, but definitely more complicated.
2) What the pipemenus can do if they're run by a user after installation. At that point the user might have made all kinds of changes, including changing ~/.conkyrc from a symlink into a real file. Hence my suggestion above. For example, fonts.conf has recently moved from ~/ to ~/.config/fontsconf. Some app or other (on Jessie) moved my file to the new location and left a symlink at ~/.fonts.conf pointing there. With the menus we can make it easy for users to edit their default conky in its new location, but of course we can't stop them changing what they want. The important thing from _conky's_ point of view is that ~/.conkyrc should exist, either as  a real file or a valid symlink.

About the default conky config file _name_ I have no opinion at all. I just used 'default' as a placeholder.

Maybe we need a helpfile about how to use this stuff?

**Comment by capn-damo** [comment]
bl-conkyzen and bl-tint2zen can both be used to reload conkys or tint2s, either via commands or a menu entry. They can also stop/start chosen individual processes, so a conkywonky or tint2restart are no longer needed imo.
The most recent tint2 and conky pipemenus have all that, as well as lots of other goodies for editing, saving sessions etc.

The scripts assume that `~/.config/conky/` and `~/.config/tint2/` have the default configs (and are the containing directories for all the configs), and if nothing is found bl-conkyzen runs `conky -q`. 
If I understand what you are saying, there should be a check for `~/.conkyrc` as well (but if it isn't found, everything else is probably missing as well!).
The conky pipemenu needs something at `~/.conkyrc` because there is an option to edit the default conkyrc.
I don't understand why it should be moved if the user has changed it, but I can see why a symlink in ~/ to a default conky should be checked and created if necessary. If the installed default AND `~/.conkyrc` are both missing then the user has messed up!

(I did try getting conkys with `find`, but it was horribly slow loading the lists because it had to traverse all the home dirs every time.)

I've made a helpfile for conkyzen (and a menu entry for it - it opens in a text dialog). There is info in the header comments of the scripts, most of which is in the helpfile, but I could edit in more specific help about locations. (BTW is /etc/skel going to be used for installed default configs?)

**Comment by capn-damo** [comment]
Will a test like this do?

`CRC="$HOME/.conkyrc"`
`BLDEFAULT="$CONKYPATH/BL-Default.conkyrc"`
`if ! [ -e "$CRC" ];then`
`ln -s "$BLDEFAULT" "$CRC"`
`fi`

That should cover it whether or not a symlink or regular file is in ~/ ?

**Comment by johnraff** [comment]
^looks good.

Thanks for the conky helpfile, which I noticed just after posting. **bunsen-docs** has been added to the netinstall list to build.

I guess it would be good to install everything in **bunsen-conky** to ~/.config/conky too, so the scripts will have something to play with. Is there a similar collection of tint2 configs somewhere?

**Comment by capn-damo** [comment]
Sector11's idea AFAIK is to have everything in bunsen-conky in `~/.config/conky` (except for the `bin` directory - I think that is there so the conky chooser scripts are included in the zipfile).

ATM there is only the default tint2, but I was thinking of doing some variations

**Comment by Sector11** [comment]
OK ... John.  If damo has the files from /bin elsewhere - take it out of ~/.config/conky, it might be confusing if they are left in.

**Comment by johnraff** [comment]
^OK Bruce @Sector11 . If they're now obsolete I'll do that when I do the debianizing of bunsen-conky. I'll be away for a few days from tomorrow, so it might not be till next week.

@capn-damo sorry forgot to answer about /etc/skel. Stuff in there goes into new users' $HOME automatically, but the bl-user-setup script triggered by lightdm does the same. In fact there seem to be some complications about having a lot of stuff in /etc/skel - for one, all files under /etc get registered by Debian as "config files" and dpkg sometimes comes up with "do you want to accept this change" type messages after package updates...

I'm beginning to wonder if we shouldn't put all the user config files in /usr/share/bunsen/bunsen-configs/skel instead. bl-user-setup can copy them from there just as easily as from /etc/skel. @2ion do you have any views on this?
