### ISSUE TITLE
Do not use && { }, just use if

### ISSUE THREAD

**Issue by AlexDaniel** [BunsenLabs/bunsen-pipemenus#3]
This is a continuation to this discussion:
https://github.com/BunsenLabs/bunsen-pipemenus/commit/f752c5cc75ab23c8e004f34bff19a083d79a09d1#commitcomment-10089365

Although the answer was "no", I thought that I should open an issue just for a bit of peer review. Feel free to close it a tad later.

> Sure, they're not the same in compound cases. I think most people understand this.

If only this was true.

Reasons to use `&& {`:
- if you want to turn Bash into C-like language where `{ }` are used for blocks.
- `... && { ... }` is 6 characters shorter than `if ... ; then ... fi`

Reasons to use traditional ifs:
- It is safe. See [Bash Pitfall #22](http://mywiki.wooledge.org/BashPitfalls#cmd1_.26.26_cmd2_.7C.7C_cmd3)
- Consistency. `if ...; then` everywhere, there is no need to have different syntax for conditionals with `else` clause.
- You don't have to change the syntax if you just want to add `else`
- Less symbol clutter. `[[ ... ]] && {` is less readable than `if [[ ... ]]; then`
- Conventions. Traditional ifs are much more popular. (I wish I could seach for `&& {` on github, but unfortunately most search engines do not allow special symbols in search queries).

**Comment by ghost** [comment]
These are really just personal preferences or choices that should be made for the sake of following a particular coding style.

Since we don't strive after keeping the scripts sh(1) or dash(1) compatible -- as clearly indicated by #!/bin/bash hashbang -- I do not see any reason to go around and change random scripts just for the sake of syntax without improving on or changing functionality, especially if the code is not unnecessarily complex (it's not).

Individual contributors may implement such changes as they see fit.

**Comment by AlexDaniel** [comment]
> Since we don't strive after keeping the scripts sh(1) or dash(1) compatible -- as clearly indicated by #!/bin/bash hashbang

How is this related?

> I do not see any reason to go around and change random scripts just for the sake of syntax without improving on or changing functionality

Luckily this kind of style is not used in any #! scripts besides bl-recent-files-pipemenu and bl-places-pipemenu, but it seems like @johnraff will eventually change the style to his own. I am a bit confused, are you agreeing or disagreeing? Here is the quote:

> ...in fact, for consistency (and my preferred code style) I was thinking of changing most of the other if constructions to && or || ...

Hm.

> Individual contributors may implement such changes as they see fit.

Consistency, please.

**Comment by AlexDaniel** [comment]
Oh, I've just noticed that bl-places-pipemenu and bl-recent-files-pipemenu were written by @johnraff. The reason why these scripts were not touched during the refactoring is because they are full of weird stuff: **exec**s, unneeded subshells, _insane_ use of external tools like perl and awk, even broken indentation. I decided not to touch these files because it is just too easy to make them fall apart.

And you know what? I took a glance over these files again and... I give up. Just let @johnraff handle the rest of the scripts. Why am I even wasting my time here.

**Comment by ghost** [comment]
OK, admittedly the scripts (which are already older) are kind of messy.

Thank you for raising this issue, it's been duly noted and your arguments are not invalid -- should message have been coming across, I'm sorry. You do not need to put your energy into convincing us of the advantages of cleanly written code -- it's clear that what we've got has its ups and downs. Valid point.

Please note however, and IMHO it makes sense, that a bug report saying Rewrite All The Scripts is not going to achieve anything since the code won't change unless somebody actually gets to it, all of it. If I were to rework some of them, I'd write it differently. John probably would do so, too.

**Comment by AlexDaniel** [comment]
@2ion Thanks for your friendly reply. But I feel like you didn't even read my previous post.
I'm not saying "Rewrite All The Scripts". I am saying "Please Do Not Rewrite All The Scripts".

It is possible that you misread my previous quote. Therefore, here is a screenshot:
![johnraff's quote from discussion](http://files.progarm.org/2015-03-08-232847_566x271_scrot.png)

I'm trying to say that we shouldn't convert the whole code into some weird collection of bad practices (either intentionally or gradually). Additionally, it would be great if the code was more or less consistent (therefore the title is `Do not use && { }, just use if`). I'm not asking anyone to do more work. Just please, if you're contributing something, do not force your made up code tricks onto existing code base with well-known conventions (which are, by the way, original language structures).

**Comment by ghost** [comment]
@AlexDaniel I guess that's to your liking ^^ Check out my change proposal at https://github.com/2ion/bunsen-pipemenus/blob/bl-recent-files-pipemenu-rewrite/bl-recent-files-pipemenu .

**Comment by johnraff** [comment]
"...in fact, for consistency (and my preferred code style) I was thinking of changing most of the other if constructions to && or || ..."

Yes it's always a mistake to attempt humour in situations like this. There was only one place I had in mind.

More important, I feel some of your comments about the places and recent-files menus are quite unjustified. Yes, they could be rewritten to look nicer, but:

perl. The only use of that was:
use perl to decode urlencoded characters
files=$(perl -MURI::Escape -e 'print uri_unescape($ARGV[0]);' "$files")
I suppose you're arguing that a bash substitution would work, but I have to deal with files with Japanese names. The perl call decodes any kanji characters, and is very fast - try it.

The only use of awk was in recent-files, where in fact it does most of the work (again, very fast). I really fail to see how either of these uses could be described as insane.

The main criterion at the time (2010) was execution time. A pipemenu had to pup up as near to instantaneously as possible. By using sh in the places menu instead of bash the execution time was about halved. The price was that parameter substitution ala bash wasn't available, meaning a call to sed for escaping. Even so, the move to dash was justified because the escaping was only done when needed, and the time cost of the external call was small. Functions were removed for the same reason. The code looks messier but runs faster. (Extensive testing was done.)

I launched file open commands with exec believing that it was better to leave the script behind at that point and have one fewer process running. I am ready to be convinced if there are reasons why it isn't a good idea.

I've just had another look, but was unable to find the "unneeded subshells" of which you speak. EDIT: Ah the tac | awk pipe. Yes, that could be replaced by a herestring or process substitution.

Sorry about the indentation.

**Comment by AlexDaniel** [comment]
Sorry for the time it took me to start writing a response.
So, I will try to show what I mean by doing some refactoring on **bl-recent-files-pipemenu**. Not that **bl-places-pipemenu** is better (in fact, I find it uglier), but I think that I can show some ideas on a smaller file in a more meaningful way.
It is not that there is something wrong with some particular feature. For example, execs (I have to mention it separately because there are no execs on in **bl-recent-files-pipemenu**) are okay by themselves, but the fact that you're using it needlessly is the problem. Why do you want to run every program through your script? Just run that program directly. Sure it works, but that's why I said "full of weird stuff", not "full of incorrect stuff".

#### Step 1

Now, the first thing that I do is elimination of syntatic mess. This includes removal of unneeded stuff, changing everything to one convention (so that similar code looks similar), removal of obviously wrong stuff, etc.

In case of bl-recent-files-pipemenu, there is not much to change. But here are some things:

``` bash
printf '%s' "$output"  # printf because echo sometimes eats backslashes
```

The comment is wrong. Unless `-e` option is in effect, `echo` will not eat backslashes in any way.
However, there is [Bash Pitfall #14](http://mywiki.wooledge.org/BashPitfalls#echo_.24foo) that is related. So either change the comment or remove it completely.

Now about printing stuff:

``` bash
output='<openbox_pipe_menu>
'"$files"'
<separator />
    <item label="Clear Recent Files">
        <action name="Execute">
            <command>
            &apos;'"$0"'&apos; --clear
            </command>
        </action>
    </item>
</openbox_pipe_menu>
'
printf '%s' "$output"
```

Two style problems here. First of all, whenever I see a string that starts with `'` I consider it to be a plain non-interpolated string. What I don't expect is that there is some `'"$var"'` stuff hidden somewhere inside of it. By eliminating such code you release some of the cognitive load that is required to parse your code with the eyes.

However, that's not the only thing! Look, you're building a string just to print it. All these string manipulations... just what for? If you have something to print -- just print it! There is no need to keep it in a variable.

This problem is even more obvious in [bl-places-pipemenu](https://github.com/BunsenLabs/bunsen-pipemenus/blob/master/bl-places-pipemenu#L159).

Not that it is wrong, but it increases code complexity, increases cognitive load and even has an impact on performance. (Throwing huge data from one string to another definitely has an impact on performance and memory use (although it is pretty small, I guess)).

Also, if we unwrap the whole thing into separate commands, you will not have to use trailing quotes like this:

``` bash
output+='stuff
'
```

Because the newline will be added automatically by `echo`.

Here you have an unquoted variable:

``` bash
elif [ $XDG_DATA_HOME ] && [ -r "${XDG_DATA_HOME}/recently-used.xbel" ]
```

See [Bash Pitfall #4](http://mywiki.wooledge.org/BashPitfalls#A.5B_.24foo_.3D_.22bar.22_.5D). Of course, it is pretty unlikely that the path to `$XDG_DATA_HOME` will contain a space (although still possible), but it is a bash error.

Things like:

``` bash
"${file_path}"
```

That's just a noise. Such style is propagated by google style guide (a guide written by people who think that you're stupid enough not to understand two exceptions when ${} is actually required, but at the same time these guys don't even know how to quote variables correctly). If that made any sense then we would be doing the same thing in perl and php, but we don't.

That's the end of step 1. Nothing cool was done, really.

#### Step 2

More serious stuff, pay attention to everything besides the awk script:

``` bash
files=$( tac "${file_path}" |  awk -v MAX="$maximum_entries" -v PR="$pre" -v MI="$mid" -v PO="$post" 'BEGIN {
    RS="</bookmark>";
    FS="<info>";
}
(NR == MAX) {exit}
!/<bookmark/ {next}
!/href=[\"'\'']file:\/\// {next}
# $1 is the command, $2 the file path
{
    sub(/count=\".*$/,"",$1)
    sub(/^.*exec=\"\&apos\;/,"",$1)
    sub(/&apos\;.*$/,"",$1)
    sub(/\%.*$/,"",$1)
    sub(/ *$/,"",$1)
    sub(/^.*file:\/\//,"",$2)
    sub(/[\"'\''].*$/,"",$2)
    gsub(/%22/,"\\&quot;",$2)
    gsub(/%3C/,"\\&lt;",$2)
    gsub(/%3E/,"\\&gt;",$2)
    name=$2
    sub(/^.*\//,"",name)
    gsub(/_/,"__",name)
    gsub(/\&apos;/,"\\&apos;\\&quot;\\&apos;\\&quot;\\&apos;",$2)
    print (PR name MI $1 " &apos;" $2 "&apos;" PO)
}' )

# use perl to decode urlencoded characters
files=$(perl -MURI::Escape -e 'print uri_unescape($ARGV[0]);' "$files")
```

Again, not that it is wrong, but you've just slurped the output of `awk` into a variable just to throw it into perl. That sounds like a pipe, right? (command substitution is done by creating a subshell, at least by definition. Usually I say "unneeded subshells" when referring to lots of needless pipes and command substitutions. I might be wrong in using that word though)
Now look! If we use a pipe, then the code becomes so much simpler! You don't even need printf, you don't need to store anything, you don't even have to use command substitutions!

The whole file will look like this:

``` bash
#!/bin/sh
#    bl-recent-files-pipemenu - a script to parse recently-used.xbel
#    and generate an openbox pipe menu
#    Copyright (C) 2010  John Crawley
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#    version 2015/01/29-bl

# Usage: add
# <menu id="recent" label="Recent Files" execute="/path/to/bl-recent-files-pipemenu" />
# to your .config/openbox/menu.xml, or use with bl-places-pipemenu (see comments there)

maximum_entries=15 # max. number of entries in menu

#######################################################################

# look for recently-used.xbel
if [ "$XDG_DATA_HOME" ] && [ -r "$XDG_DATA_HOME/recently-used.xbel" ]; then
    file_path="$XDG_DATA_HOME/recently-used.xbel"
elif [ -r "$HOME/.local/share/recently-used.xbel" ]; then
    file_path="$HOME/.local/share/recently-used.xbel"
elif [ -r "$HOME/.recently-used.xbel" ]; then
    file_path="$HOME/.recently-used.xbel"
else
    echo "$0: cannot find a readable recently-used.xbel file" >&2
    echo '<openbox_pipe_menu>
<separator label="No recently-used.xbel file found." />
</openbox_pipe_menu>'
    exit 1
fi

# if argument is --clear, empty .recently-used.xbel
if [ "$1" = '--clear' ]; then
    cat << ':EOF' > "$file_path"
<?xml version="1.0" encoding="UTF-8"?>
<xbel version="1.0"
      xmlns:bookmark="http://www.freedesktop.org/standards/desktop-bookmarks"
      xmlns:mime="http://www.freedesktop.org/standards/shared-mime-info"
>
</xbel>
:EOF
    exit
fi

pre='    <item label="'
mid='">
        <action name="Execute">
            <command>
            '
post='
            </command>
        </action>
    </item>'

echo '<openbox_pipe_menu>'

tac "$file_path" |
    awk -v MAX="$((maximum_entries + 2))" -v PR="$pre" \
    -v MI="$mid" -v PO="$post" 'BEGIN {
    RS="</bookmark>";
    FS="<info>";
}
(NR == MAX) {exit}
!/<bookmark/ {next}
!/href=[\"'\'']file:\/\// {next}
# $1 is the command, $2 the file path
{
    sub(/count=\".*$/,"",$1)
    sub(/^.*exec=\"\&apos\;/,"",$1)
    sub(/&apos\;.*$/,"",$1)
    sub(/\%.*$/,"",$1)
    sub(/ *$/,"",$1)
    sub(/^.*file:\/\//,"",$2)
    sub(/[\"'\''].*$/,"",$2)
    gsub(/%22/,"\\&quot;",$2)
    gsub(/%3C/,"\\&lt;",$2)
    gsub(/%3E/,"\\&gt;",$2)
    name=$2
    sub(/^.*\//,"",name)
    gsub(/_/,"__",name)
    gsub(/\&apos;/,"\\&apos;\\&quot;\\&apos;\\&quot;\\&apos;",$2)
    print (PR name MI $1 " &apos;" $2 "&apos;" PO)
}' | perl -MURI::Escape -ne 'print uri_unescape($_)'

echo '<separator />
    <item label="Clear Recent Files">
        <action name="Execute">
            <command>'
echo "            &apos;$0&apos; --clear"
echo '            </command>
        </action>
    </item>
</openbox_pipe_menu>'
```

Yeah! Much simpler. And it outputs exactly the same thing as your older version.
And not only it is more correct, it should also work a bit faster. We don't have to wait for perl to initialize its thing, we're already processing stuff with awk! And since we're processing it line by line, once you've done reading a file, the whole thing is already printed to stdout. I really hope that tac is capable of printing the file right away and does not slurp the whole file in.

If you want to do some extreme benchmarking, feel free to do so! I'm pretty sure that this code works faster or at least just as fast as your old code.

#### Step 3

All of the previous steps were done just by looking at the code, without really figuring out what the code actually does (but note that we've already shortened the code and made it work faster, just by changing the syntax a little bit). First of all, we have Perl that is using `URI::Escape`. We might cut off some milliseconds if we throw away that module. If you [look at the docs](http://search.cpan.org/~gaas/URI/URI/Escape.pm) you will see that the code is **almost** equivalent to `$string =~ s/%([0-9A-Fa-f]{2})/chr(hex($1))/eg;`. Let's try that!

``` bash
}' | perl -ne 's/%([0-9A-Fa-f]{2})/chr(hex($1))/eg; print'
```

This code runs from two to three times faster (7ms instead of 19ms) on my machine. I don't think that we should actually care about such difference, but if you care about performance THAT MUCH -- there you go!

I've tested that code with kanji characters -- it works. At least as far as I can see.

Okay! Now, if you look at that pipe, you'll notice that you have

```
tac | awk | perl
```

And all that is running in sh. Well, a rule of thumb is that you should try to avoid piping any two of these tools: perl, python, bash, awk, sed, cut and some others. The reason is simple -- most of these tools have overlapping functionality. If you follow that simple rule your life will get so much better!

Well, apparently we cannot replace all this stuff with shell functions. Maybe move the perl part into awk? It should probably look like (in a perfect world):

``` awk
    $2=gensub(/%([0-9A-Fa-f]{2})/, sprintf("%c", "0x\\1"), "g", $2)
```

But obviously it does not work because awk does not allow you to access captured groups like this. Eh.
But look, all that awk does is just some replacements! We can do that in `perl` for sure. And it will also get much more readable :)

In fact, if you actually do that, you'll notice that the biggest part of your script is perl code (other stuff being just `echo`s and argument checking). And this means that you'd better write the whole thing in perl :)

Well, I'm not going to do that now. This comment is already too long and you will probably say all this stuff is a matter of preference. Well, okay... I hope that it was a nice thing to read anyway.

#### Step 4

Alright, even if you rewrite the whole thing in perl, what you should understand is that xml is your input and the output is xml as well.
You know which tool does that? XSLT. You are still going to need some other tool to run it though. But at least this way you are not going to reinvent the wheel. Some investigation is required in order to see how feasible it is, but hey, that's as deep as you can go.

There are some other minor problems with the current script, but I usually leave some stuff behind. There is a chance that my changes will not get anywhere (either the changes are going to be denied or the whole script will be rewritten), so I'm not wasting my time on some tiny details.

@2ion god, that is verbose! I really like that xpath is being used. And the whole thing is written very nicely, except [read without -r](http://wiki.bash-hackers.org/commands/builtin/read#read_without_-r), eval (huh? I'm not sure if there was any need in that. Maybe there is a reason), [file paths being passed as parameters without --](http://mywiki.wooledge.org/BashPitfalls#cp_.24file_.24target) and the fact that the whole script is really long is kinda sad.

@johnraff I think that now it should be clear what I meant. Your guess that I meant herestring or process substitution is pretty weird, I don't think that there is a big benefit in that and I'm pretty sure that these things are not available in dash.

Lastly I want to say that all these changes are so tiny, but when you add it all up the result is much better.
Have a nice week, guys!

**Comment by johnraff** [comment]
@AlexDaniel thank you for taking the time to go over that script. While there are always going to be issues that come down to differences of taste, most of your points are quite valid, and some of the changes will indeed be implemented.

Anyway, "Step 2" of your revisions works fine, and runs slightly faster than the original. (~22ms vs 20ms with a 360 line xbel file.) About execution time - please remember that this, and "places", were written 10 years ago when processors were slower and a quick response was perhaps more **important** than today. 20 vs 30ms is less of an issue than 100 vs 150ms. 
BTW I just found another faster way of unescaping urlcode, from /usr/bin/xdg-open:

```
printf "$(sed -e 's@%\([a-f0-9A-F]\{2\}\)@\\x\1@g' <<<"$file")"
```

Basically, though, I don't think a major rewrite of the script is worth spending time on unless it parses the xml strictly, which the tac | awk approach is definitely not doing.

About collecting output in a variable vs spitting it out as you go along. That just seems to me a cleaner way of going about things. You clearly disagreee. In particular, I find the use of repeated calls to echo just to get linebreaks a bit irritating. Even more so, calling say() which in turn calls the external executable fold, just for a linebreak in the output, seems to me incredibly inelegant. As I said, tastes differ.

About exec. We still don't seem to understand each other on this. I used exec in the places menu like this

```
exec "$text_editor" "$1"
```

_precisely_ because I wanted to run $text_editor directly, without running it through the script. As 'help exec' says, to "Replace the shell with the given command". After using exec the original process no longer exists, avoiding spawning a new one.

About the "eating backslashes" comment with echo: I will remove that, but, at least at the time it was made, there were definitely issues with **echo** as could be seen by googling. Even the BashWiki article you link to says "The only absolutely sure way to print the value of a variable is using printf" and another quick search just turned up this: http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo/65819#65819
